version: "3.8"

services:
  backend:
    image: escolamusica-backend
    build:
      context: ./src/back/EscolaMusica
      dockerfile: EscolaMusica/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    image: escolamusica-frontend
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"