#name: "DEV DEPLOY"
#
#on:
#  push:
#    branches-ignore:
#      - main
#
#  pull_request:
#    branches:
#      - main
#
#permissions:
#  id-token: write
#  contents: read
#  pull-requests: write
#
#jobs:
#
#  terraform:
#    uses: ./.github/workflows/terraform.yml
